### ISSUE TITLE
Feedback on Script 51

### ISSUE THREAD

**Issue by bethSQL** [gwalkey/SQLTranscriptase#13]
Thanks for script 51 -- it looks very handy. Ran it on a couple of challenging servers:

Did not handle/skip local group:
Error Getting ADGroup Member - Sysadmins [<SERVER>\PRD_LocalAdmin]
Error: [Cannot find an object with identity: '<SERVER>\PRD_LocalAdmin' under: 'DC=<DOMAIN>,DC=xxx,DC=xxx'.]

Case sensitive instance:
The multi-part identifier "l.name" could not be bound.
... and more ... 
[lines 380-396 need case consistency on table aliases l and p]

My line numbers are going to be off a hair from yours. Failed to mention that in earlier issues. Sorry.

**Comment by gwalkey** [comment]
The Code is provided as-is
