### ISSUE TITLE
Assembly Path is hard coded in 21_DAC_packages and 22_PBM

### ISSUE THREAD

**Issue by hada79** [gwalkey/SQLTranscriptase#7]
I get errors running these two scripts because it is hard coded to look in the 120 folder. Maybe it could check which SQL version is running and choose the folder accordingly?

21_Dack_Packages.ps1 - Line 71
22_Policy_Based_Mgmt.ps1 - Line 57

I have really enjoyed these scripts George! Thanks a lot for sharing!

**Comment by gwalkey** [comment]
Thanks for the feedback!

Ill go back and use the same Version-Detection code in lines 154-185 in 21_DAC
and similar for 22_PBM.

(Unless those DLLs are NOT in previous versions!)

Im currently on SQL 2014 SP1 CU3
Thanks!
