### ISSUE TITLE
Error Out on 10_SSAS_Objects.ps1 

### ISSUE THREAD

**Issue by mailMaheshGupta** [gwalkey/SQLTranscriptase#8]
It took some time to work on this but once you see the output, I am amazed, how well it's prepared but I am yet to analyze the Output like the validity of Output like Credentials Passwords or link server passwords, etc...  Any way, my issue is specifically master script 00_RunAllScripts.ps1 errors out at step 10, when it try to execute 10_SSAS_Objects.ps1

**Error is** 
10 - SSAS Objects
Server: [localhost]
Cant Find the AMO/TMO namespace libraries
At C:\Temp\Nuget\SQLTranscriptase-master\Scripts\10_SSAS_Objects.ps1:96 char:5
+     Throw('Cant Find the AMO/TMO namespace libraries')
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Cant Find the A...space libraries:String) [], RuntimeException
    + FullyQualifiedErrorId : Cant Find the AMO/TMO namespace libraries
 
Note: 
This error is even coming even after installing SSAS AMOD package, anything else needs to be extracted?

Install-Package Microsoft.AnalysisServices.AdomdClient.retail.amd64
Install-Package Microsoft.AnalysisServices.retail.amd64 -Version 18.7.0.1

**Comment by gwalkey** [comment]
The Add-Type on line 99 is fixed to SQL Server 2019 (version 15)
Once you change that to match the version of those 3 DLLs to match your installed versions,
it should work (Or install SQL 2019 Developer on your box)
thanks!
